### ISSUE TITLE
Documentation of registers

### ISSUE THREAD

**Issue by h3llrais3r** [paolosabatino/saj-mqtt#2]
Hi Paolo, can you provide the documentation you used for parsing the registers?
I'm checking the parsed data and see some weird results, so I'm wondering if I have the same modbus documentation as you.
I also see a few times in my documentation that the register is a uint16 (struct H) while in the parsedata.py, it unpacks it as int16 (struct h).

Example:
![image](https://github.com/paolosabatino/saj-mqtt/assets/1945295/50aeeee6-d835-4b39-8356-6063224346d4)

So according to my documentation it should be like this (second line) but then the numbers seems to be totally incorrect:
![image](https://github.com/paolosabatino/saj-mqtt/assets/1945295/a99ece50-6e60-4063-a57b-4c90dba01d23)

with your format:
Grid data:
Voltage: 228.1V         Current: -1.440A                Frequency: 49.98Hz
DC current: -372ma      Active power: -79W      Apparent power: 328W    Power factor: -0.2

with the format according to my documentation:
Grid data:
Voltage: 228.1V         Current: 653.920A               Frequency: 49.98Hz
DC current: -372ma      Active power: 65457W    Apparent power: 328W    Power factor: -0.2

**Comment by paolosabatino** [comment]
Simply enough, the documentation of some registers is just wrong. There are several int/uint mismatches, but also registers that are documented in the PDF have no correspondence with real data or some registers exposed by the inverter are not documented in the PDF - for example, the readings for the external Smart Meter.

Most of them, though, are correct and useful.

**Comment by h3llrais3r** [comment]
Thanks for the info, so I suppose you are also using the document `4_5868569929443185242.pdf` which dates from 2020? (Document Number: J-RD-SW-G-1503001)

**Comment by paolosabatino** [comment]
Yes,it is from 5 sep. 2020

**Comment by h3llrais3r** [comment]
Ok, thx, then we have the same documentation.
