### ISSUE TITLE
Writing of registers

### ISSUE THREAD

**Issue by h3llrais3r** [paolosabatino/saj-mqtt#4]
Hi Paolo, I'm trying to improve a bit more on the integration so I have another question.
Until now, I haven't used the `write_register` functionality, but I like to start using it.
However, most of the R/W registers are uint16, but a few ones are HEX.
![image](https://github.com/user-attachments/assets/85b72315-aeac-441c-a0ce-acd6431fbf5e)
![image](https://github.com/user-attachments/assets/5df5f552-6001-4be6-b531-86d70558cf0c)
Do you know if the `write_register` code would work for those as well?
I suppose yes (as the size is the same), but wanted to know if you also already have tried to write other registers besides unit16.
Thanks for your feedback.

**Comment by MartinDRZ** [comment]
It does work - I set 3606 and 3607 multiple times per day with no issues.

Read the column about how the time works carefully...

**Comment by h3llrais3r** [comment]
What about the 3608? Because for the 3606 and 3607, we have some examples:
I'm using `0x0000` and `0x0500` for 00h00 till 05h00.
Those registers are quite fixed for me, I rather want to change the charging power dynamically.
I typically want it on workdays (00011111 binary), so that should be `0x1f`.
I have percentage of 20% of the standard power, which should be `0x14`.
The 2 above combined should become `0x1f14`? So I should write `7956` int value to the register?

Some info I found on the internet related to the calendar in binary format:
To decode 7F which represents 0SSFTWTM (1 byte = 8 bits)
7F (Hex days of the week) =127 (decimal) =01111111 (binary)  = 0SuSaFrThWeTuMo
7 bits of a 8 digit binary value is used to represent the day on in the schedule…

M=1 = 0x1 = 1
T=10 = 0x2 = 2
W=100 = 0x4 = 4
T=1000 = 0x8 = 8
F=10000 = 0x10 = 16
S=100000 = 0x20 = 32
S=1000000 = 0x40 = 64
0SSFTWTM=01111111 = 0x7f = 127

**Comment by paolosabatino** [comment]
Hello,

it will work indeed!

UInt16 is a recognizable and expected integer format, `HEX` is out of context and IMHO also an error in the documentation because it is not an integer format, but a number representation in a specified base.

You can fetch either base-10 `7956` or base-16 `0x1f14` number to the `readregs.py` and `writereg.py` utilities because they have [this function](https://github.com/paolosabatino/saj-mqtt/blob/main/writereg.py#L14-L23) to normalize the representation.

You can also see the usage in the writereg.py [usage example](https://github.com/paolosabatino/saj-mqtt/blob/main/writereg.py#L26-L29)

If you are programming with `sajmqtt.py` library, you need not to worry about since, as said, the representation of the number does not change the number itself:

```python
>>> a=0x1f14 # Hex for 7956
>>> print(a)
7956 # Decimal
>>> print(bin(a))
0b1111100010100 # Binary for 7956
>>> 
```

**Comment by h3llrais3r** [comment]
Anyone already played with the days of week?
Is my assumption correct on how the days of week are stored in a binary way?

**Comment by paolosabatino** [comment]
@h3llrais3r sorry but I never tried with days of week, but your assumption seems correct. Also the documentation says that the days of week stays in the high byte and the power in low byte, so I guess for example that wednesday at 20% power should be written as `(0x4 << 8) | (0x14) = 0x414`

**Comment by h3llrais3r** [comment]
Thanks, will try it out in the coming days. Will keep you posted here.

**Comment by MartinDRZ** [comment]
Don't forget that you can just set the configuration via the app and read the register to see if the values match up to what you expect to see. If it aligns with your expectations then you know what to do. If it doesn't, you have some data to figure it out from.

**Comment by h3llrais3r** [comment]
One thing I noticed as well, and really annoys me, is that the time on the inverter is running slower than real time.
You know if there is any way to keep the time in sync?
Or can it only be set on the inverter itself?

**Comment by h3llrais3r** [comment]
> Thanks, will try it out in the coming days. Will keep you posted here.

Sorry for late reply: I've just tried it out by writing `0x1f28` to register `0x3608`, which has put my charge to 40% for every working day (ma - fr).

PS: I've set it via the service/action I've added ha integration (`saj_mqtt.write_register`). 
![image](https://github.com/user-attachments/assets/800f4e1b-a077-40bd-b15b-c157d439fc46)
